version: '3.1'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
          - '7777:5432'
    volumes:
          - ./data:/var/lib/postgresql
    environment:
          - POSTGRES_RANDOM_ROOT_PASSWORD=yes
          - POSTGRES_DATABASE=app
          - POSTGRES_USER=new
          - POSTGRES_PASSWORD=12345u







